#!/usr/bin/env python
"""Definitions and properties of amino acids for Peptide Library Package"""

# Natural Amino Acids:

aminos = {
    "Glycine": {
        "Code": "Gly",
        "Formula": "C2H5NO2",
        "Letter": "G",
        "MolWeight": "75.07",
        "SMILES": "NCC(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Alanine": {
        "Code": "Ala",
        "Formula": "C3H7NO2",
        "Letter": "A",
        "MolWeight": "89.09",
        "SMILES": "N[C@@]([H])(C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Arginine": {
        "Code": "Arg",
        "Formula": "C6H14N4O2",
        "Letter": "R",
        "MolWeight": "174.20",
        "SMILES": "N[C@@]([H])(CCCNC(=N)N)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Asparagine": {
        "Code": "Asn",
        "Formula": "C4H8N2O3",
        "Letter": "N",
        "MolWeight": "132.12",
        "SMILES": "N[C@@]([H])(CC(=O)N)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Aspartic_Acid": {
        "Code": "Asp",
        "Formula": "C4H7NO4",
        "Letter": "D",
        "MolWeight": "133.10",
        "SMILES": "N[C@@]([H])(CC(=O)O)C(=O)O",
        "cterm": "N[C@@]([H])(CC*(=O))C(=O)O",
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Cysteine": {
        "Code": "Cys",
        "Formula": "C3H7NO2S",
        "Letter": "C",
        "MolWeight": "121.16",
        "SMILES": "N[C@@]([H])(CS)C(=O)O",
        "cterm": False,
        "disulphide": "N[C@@]([H])(CS*)C(=O)O",
        "ester": False,
        "nterm": False,
    },
    "L-Glutamic_Acid": {
        "Code": "Glu",
        "Formula": "C5H9NO4",
        "Letter": "E",
        "MolWeight": "147.13",
        "SMILES": "N[C@@]([H])(CCC(=O)O)C(=O)O",
        "cterm": "N[C@@]([H])(CCC*(=O))C(=O)O",
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Glutamine": {
        "Code": "Gln",
        "Formula": "C5H10N2O3",
        "Letter": "Q",
        "MolWeight": "146.15",
        "SMILES": "N[C@@]([H])(CCC(=O)N)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Histidine": {
        "Code": "His",
        "Formula": "C6H9N3O2",
        "Letter": "H",
        "MolWeight": "155.16",
        "SMILES": "N[C@@]([H])(CC1=CN=C-N1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Isoleucine": {
        "Code": "Ile",
        "Formula": "C6H13NO2",
        "Letter": "I",
        "MolWeight": "131.18",
        "SMILES": "N[C@@]([H])([C@]([H])(CC)C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Leucine": {
        "Code": "Leu",
        "Formula": "C6H13NO2",
        "Letter": "L",
        "MolWeight": "131.18",
        "SMILES": "N[C@@]([H])(CC(C)C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Lysine": {
        "Code": "Lys",
        "Formula": "C6H12N2O2",
        "Letter": "K",
        "MolWeight": "146.19",
        "SMILES": "N[C@@]([H])(CCCCN)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": "N[C@@]([H])(CCCCN*)C(=O)O",
    },
    "L-Methionine": {
        "Code": "Met",
        "Formula": "C5H11NO2S",
        "Letter": "M",
        "MolWeight": "149.21",
        "SMILES": "N[C@@]([H])(CCSC)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Phenylalanine": {
        "Code": "Phe",
        "Formula": "C9H11NO2",
        "Letter": "F",
        "MolWeight": "165.19",
        "SMILES": "N[C@@]([H])(Cc1ccccc1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Proline": {
        "Code": "Pro",
        "Formula": "C5H9NO2",
        "Letter": "P",
        "MolWeight": "115.13",
        "SMILES": "N1[C@@]([H])(CCC1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Serine": {
        "Code": "Ser",
        "Formula": "C3H7NO2",
        "Letter": "S",
        "MolWeight": "105.09",
        "SMILES": "N[C@@]([H])(CO)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": "N[C@@]([H])(CO*)C(=O)O",
        "nterm": False,
    },
    "L-Threonine": {
        "Code": "Thr",
        "Formula": "C4H9NO3",
        "Letter": "T",
        "MolWeight": "119.12",
        "SMILES": "N[C@@]([H])([C@]([H])(O)C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": "N[C@@]([H])([C@]([H])(O*)C)C(=O)O",
        "nterm": False,
    },
    "L-Tryptophan": {
        "Code": "Trp",
        "Formula": "C11H12N2O2",
        "Letter": "W",
        "MolWeight": "204.23",
        "SMILES": "N[C@@]([H])(CC(=CN2)C1=C2C=CC=C1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Tyrosine": {
        "Code": "Tyr",
        "Formula": "C9H11NO3",
        "Letter": "Y",
        "MolWeight": "181.19",
        "SMILES": "N[C@@]([H])(Cc1ccc(O)cc1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": "N[C@@]([H])(Cc1ccc(O*)cc1)C(=O)O",
        "nterm": False,
    },
    "L-Valine": {
        "Code": "Val",
        "Formula": "C5H11NO2",
        "Letter": "V",
        "MolWeight": "117.15",
        "SMILES": "N[C@@]([H])(C(C)C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
}

# Opposite chirality aminos

d_aminos = {
    "D-Alanine": {
        "Code": "ala",
        "Formula": "C3H7NO2",
        "Letter": "a",
        "MolWeight": "89.09",
        "SMILES": "N[C@]([H])(C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Arginine": {
        "Code": "arg",
        "Formula": "C6H14N4O2",
        "Letter": "r",
        "MolWeight": "174.20",
        "SMILES": "N[C@]([H])(CCCNC(=N)N)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Asparagine": {
        "Code": "asn",
        "Formula": "C4H8N2O3",
        "Letter": "n",
        "MolWeight": "132.12",
        "SMILES": "N[C@]([H])(CC(=O)N)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Aspartic_Acid": {
        "Code": "asp",
        "Formula": "C4H7NO4",
        "Letter": "d",
        "MolWeight": "133.10",
        "SMILES": "N[C@]([H])(CC(=O)O)C(=O)O",
        "cterm": "N[C@]([H])(CC*(=O))C(=O)O",
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Cysteine": {
        "Code": "cys",
        "Formula": "C3H7NO2S",
        "Letter": "c",
        "MolWeight": "121.16",
        "SMILES": "N[C@]([H])(CS)C(=O)O",
        "cterm": False,
        "disulphide": "N[C@]([H])(CS*)C(=O)O",
        "ester": False,
        "nterm": False,
    },
    "D-Glutamic_Acid": {
        "Code": "glu",
        "Formula": "C5H9NO4",
        "Letter": "e",
        "MolWeight": "147.13",
        "SMILES": "N[C@]([H])(CCC(=O)O)C(=O)O",
        "cterm": "N[C@]([H])(CCC*(=O))C(=O)O",
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Glutamine": {
        "Code": "gln",
        "Formula": "C5H10N2O3",
        "Letter": "q",
        "MolWeight": "146.15",
        "SMILES": "N[C@]([H])(CCC(=O)N)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Histidine": {
        "Code": "his",
        "Formula": "C6H9N3O2",
        "Letter": "h",
        "MolWeight": "155.16",
        "SMILES": "N[C@]([H])(CC1=CN=C-N1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Isoleucine": {
        "Code": "ile",
        "Formula": "C6H13NO2",
        "Letter": "i",
        "MolWeight": "131.18",
        "SMILES": "N[C@]([H])([C@@]([H])(CC)C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Leucine": {
        "Code": "leu",
        "Formula": "C6H13NO2",
        "Letter": "l",
        "MolWeight": "131.18",
        "SMILES": "N[C@]([H])(CC(C)C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Lysine": {
        "Code": "lys",
        "Formula": "C6H12N2O2",
        "Letter": "k",
        "MolWeight": "146.19",
        "SMILES": "N[C@]([H])(CCCCN)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": "N[C@]([H])(CCCCN*)C(=O)O",
    },
    "D-Methionine": {
        "Code": "met",
        "Formula": "C5H11NO2S",
        "Letter": "m",
        "MolWeight": "149.21",
        "SMILES": "N[C@]([H])(CCSC)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Phenylalanine": {
        "Code": "phe",
        "Formula": "C9H11NO2",
        "Letter": "f",
        "MolWeight": "165.19",
        "SMILES": "N[C@]([H])(Cc1ccccc1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Proline": {
        "Code": "pro",
        "Formula": "C5H9NO2",
        "Letter": "p",
        "MolWeight": "115.13",
        "SMILES": "N1[C@]([H])(CCC1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Serine": {
        "Code": "ser",
        "Formula": "C3H7NO2",
        "Letter": "s",
        "MolWeight": "105.09",
        "SMILES": "N[C@]([H])(CO)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": "N[C@]([H])(CO*)C(=O)O",
        "nterm": False,
    },
    "D-Tryptophan": {
        "Code": "trp",
        "Formula": "C11H12N2O2",
        "Letter": "w",
        "MolWeight": "204.23",
        "SMILES": "N[C@]([H])(CC(=CN2)C1=C2C=CC=C1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Tyrosine": {
        "Code": "tyr",
        "Formula": "C9H11NO3",
        "Letter": "y",
        "MolWeight": "181.19",
        "SMILES": "N[C@]([H])(Cc1ccc(O)cc1)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": "N[C@]([H])(Cc1ccc(O*)cc1)C(=O)O",
        "nterm": False,
    },
    "D-Valine": {
        "Code": "val",
        "Formula": "C5H11NO2",
        "Letter": "v",
        "MolWeight": "117.15",
        "SMILES": "N[C@]([H])(C(C)C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Threonine": {
        "Code": "thr",
        "Formula": "C4H9NO3",
        "Letter": "t",
        "MolWeight": "119.12",
        "SMILES": "N[C@]([H])([C@@]([H])(O)C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": "N[C@]([H])([C@@]([H])(O*)C)C(=O)O",
        "nterm": False,
    },
}

# Opposite chirality aminos
special_aminos = {
    "L-Diaminopropionic_Acid": {
        "Code": "Dap",
        "Formula": "C3H8N2O2",
        "Letter": "J",
        "MolWeight": "104.12",
        "SMILES": "N[C@@]([H])(CN)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": "N[C@@]([H])(CN*)C(=O)O",
    },
    "D-Diaminopropionic_Acid": {
        "Code": "dap",
        "Formula": "C3H8N2O2",
        "Letter": "j",
        "MolWeight": "104.12",
        "SMILES": "N[C@]([H])(CN)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": "N[C@]([H])(CN*)C(=O)O",
    },
    "L-Ornithine": {
        "Code": "Orn",
        "Formula": "C5H12N2O2",
        "Letter": "O",
        "MolWeight": "132.16",
        "SMILES": "N[C@@]([H])(CCCN)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": "N[C@@]([H])(CCCN*)C(=O)O",
    },
}

unnatural_aminos = {
    "L-Selenocysteine": {
        "Code": "Sec",
        "Formula": "C3H6NO2Se",
        "Letter": "U",
        "MolWeight": "168.07",
        "SMILES": "N[C@]([H])(C[Se])C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Selenocysteine": {
        "Code": "sec",
        "Formula": "C3H6NO2Se",
        "Letter": "u",
        "MolWeight": "168.07",
        "SMILES": "N[C@@]([H])(C[Se])C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Pyrrolysine": {
        "Code": "Pyl",
        "Formula": "C12H21N3O3",
        "Letter": "O",
        "MolWeight": "255.31",
        "SMILES": "N[C@@]([H])(CCCCNC(=O)[C@H]1N=CC[C@@H]1C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Pyrrolysine": {
        "Code": "pyl",
        "Formula": "C12H21N3O3",
        "Letter": "o",
        "MolWeight": "255.31",
        "SMILES": "N[C@]([H])(CCCCNC(=O)[C@H]1N=CC[C@@H]1C)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Norleucine": {
        "Code": "Nle",
        "Formula": "C6H13NO2",
        "Letter": "X",
        "MolWeight": "131.18",
        "SMILES": "N[C@@]([H])([C@]([H])CCC)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Norleucine": {
        "Code": "nle",
        "Formula": "C6H13NO2",
        "Letter": "x",
        "MolWeight": "131.18",
        "SMILES": "N[C@]([H])([C@]([H])CCC)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "L-Norvaline": {
        "Code": "Nva",
        "Formula": "C5H11NO2",
        "MolWeight": "117.15",
        "SMILES": "N[C@@]([H])(CCC)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    },
    "D-Norvaline": {
        "Code": "nva",
        "Formula": "C5H11NO2",
        "MolWeight": "117.15",
        "SMILES": "N[C@]([H])(CCC)C(=O)O",
        "cterm": False,
        "disulphide": False,
        "ester": False,
        "nterm": False,
    }
}

"N[C@H]([C@@H](CC)C)C(=O)O"

noncanonical_aminos = {
    'trans-3-hydroxy-L-proline/(2S,3S)-3-Hydroxypyrrolidine-2-carboxylic acid': { # CHECKED!
        'Code': 'Hyp3s',
        'Formula': 'C5H9NO3',
        'Letter': 'Hyp3s',
        'MolWeight': '131.058243148',
        'SMILES': 'N1[C@@H]([C@@H](O)CC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Hydroxyproline/(2S,4R)-4-Hydroxypyrrolidine-2-carboxylic acid': { # CHECKED!
        'Code': 'Hyp4r',
        'Formula': 'C5H9NO3',
        'Letter': 'Hyp4r',
        'MolWeight': '131.058243148',
        'SMILES': 'N1C[C@H](O)C[C@H]1C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Phosphoserine/(2S)-2-amino-3-phosphonooxypropanoic acid': { # CHECKED!
        'Code': 'pSer',
        'Formula': 'C3H8NO6P',
        'Letter': 'pSer',
        'MolWeight': '185.008923606',
        'SMILES': 'N[C@@H](CO[P](O)(O)=O)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S,3R)-2-amino-3-phosphonooxybutanoic acid': { # CHECKED!
        'Code': 'pThr',
        'Formula': 'C4H10NO6P',
        'Letter': 'pThr',
        'MolWeight': '199.02457367000002',
        'SMILES': 'C[C@@H](O[P](O)(O)=O)[C@H](N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2,5-diaminopentanoic acid': { # CHECKED!
        'Code': 'Orn',
        'Formula': 'C5H12N2O2',
        'Letter': 'Orn',
        'MolWeight': '132.089877624',
        'SMILES': 'NCCC[C@H](N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-5-(carbamoylamino)pentanoic acid': { # CHECKED!
        'Code': 'Cit',
        'Formula': 'C6H13N3O3',
        'Letter': 'Cit',
        'MolWeight': '175.095691276',
        'SMILES': 'N[C@@H](CCCNC(N)=O)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Argininosuccinic acid/(2S)-2-[[N′-[(4S)-4-amino-4-carboxybutyl]carbamimidoyl]amino]butanedioic acid': { # CHECKED!
        'Code': 'ArgSA',
        'Formula': 'C10H18N4O6',
        'Letter': 'ArgSA',
        'MolWeight': '290.122634296',
        'SMILES': 'N[C@@H](CCCN=C(N)N[C@@H](CC(O)=O)C(O)=O)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Ademetionine/(2S)-2-amino-4-[[(2S,3S,4R,5R)-5-(6-aminopurin-9-yl)-3,4-dihydroxyoxolan-2-yl]methyl-methylsulfonio]butanoate': { # CHECKED!
        'Code': 'SAM',
        'Formula': 'C15H22N6O5S',
        'Letter': 'SAM',
        'MolWeight': '398.1372388040001',
        'SMILES': 'N[C@H](CC[S+](C[C@H]1O[C@H]([C@H](O)[C@@H]1O)n2cnc3c(N)ncnc23)C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'S-adenosyl-L-homocysteinate/5`-S-[(3S)-3-amino-3-carboxylatopropyl]-5`-thioadenosine': { # CHECKED!
        'Code': 'SAH',
        'Formula': 'C14H19N6O5S-',
        'Letter': 'SAH',
        'MolWeight': '383.11431228791',
        'SMILES': 'N[C@@H](CCSC[C@H]1O[C@H]([C@H](O)[C@@H]1O)n2cnc3c(N)ncnc23)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Cysteinesulfinic acid/(2R)-2-amino-3-hydroxy-3-oxopropane-1-sulfinate': { # CHECKED!
        'Code': '3SA',
        'Formula': 'C3H6NO4S-',
        'Letter': '3SA',
        'MolWeight': '152.00230225191',
        'SMILES': 'N[C@@H](C[S](O)=O)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Homocysteine/(2S)-2-amino-4-sulfanylbutanoic acid': { # CHECKED!
        'Code': 'hCys/Hcy',
        'Formula': 'C4H9NO2S',
        'Letter': 'hCys/Hcy',
        'MolWeight': '135.035399528',
        'SMILES': 'N[C@@H](CCS)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Taurine/2-aminoethanesulfonic acid': { # CHECKED!
        'Code': 'Tau',
        'Formula': 'C2H7NO3S',
        'Letter': 'Tau',
        'MolWeight': '125.014664084',
        'SMILES': 'NCC[S](O)(=O)=O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Sarcosine/2-(methylamino)acetic acid': { # CHECKED!
        'Code': 'Sar',
        'Formula': 'C3H7NO2',
        'Letter': 'Sar',
        'MolWeight': '89.047678464',
        'SMILES': 'CNCC(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Anthranilic acid/2-aminobenzoic acid': { # CHECKED!
        'Code': '2AA',
        'Formula': 'C7H7NO2',
        'Letter': '2AA',
        'MolWeight': '137.047678464',
        'SMILES': 'Nc1ccccc1C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Kynurenic acid/4-oxo-1H-quinoline-2-carboxylic acid': { # CHECKED!
        'Code': 'Kyn',
        'Formula': 'C10H7NO3',
        'Letter': 'Kyn',
        'MolWeight': '189.042593084',
        'SMILES': 'N1C(=CC(=O)c2c1cccc2)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-2-Aminoadipic acid/(2S)-2-aminohexanedioic acid': { # CHECKED!
        'Code': 'Aad',
        'Formula': 'C6H11NO4',
        'Letter': 'Aad',
        'MolWeight': '161.068807832',
        'SMILES': 'N[C@@H](CCCC(O)=O)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-homoserine/(2S)-2-amino-4-hydroxybutanoic acid': { # CHECKED!
        'Code': 'hSer',
        'Formula': 'C4H9NO3',
        'Letter': 'hSer',
        'MolWeight': '119.058243148',
        'SMILES': 'N[C@@H](CCO)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'beta-Alanine/3-aminopropanoic acid': { # CHECKED!
        'Code': 'β-Ala',
        'Formula': 'C3H7NO2',
        'Letter': 'β-Ala',
        'MolWeight': '89.047678464',
        'SMILES': 'NCCC(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'D-serine/(2R)-2-amino-3-hydroxypropanoic acid': { # CHECKED!
        'Code': 'D-Ser',
        'Formula': 'C3H7NO3',
        'Letter': 'D-Ser',
        'MolWeight': '105.042593084',
        'SMILES': 'N[C@H](CO)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'D-Aspartic acid/(2R)-2-aminobutanedioic acid': { # CHECKED!
        'Code': 'D-Asp',
        'Formula': 'C4H7NO4',
        'Letter': 'D-Asp',
        'MolWeight': '133.037507704',
        'SMILES': 'N[C@H](CC(O)=O)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Gamma-Aminobutyric Acid/4-aminobutanoic acid ': { # CHECKED!
        'Code': 'GABA',
        'Formula': 'C4H9NO2',
        'Letter': 'GABA',
        'MolWeight': '103.063328528',
        'SMILES': 'NCCCC(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Levodopa/(2S)-2-amino-3-(3,4-dihydroxyphenyl)propanoic acid': { # CHECKED!
        'Code': 'DOPA',
        'Formula': 'C9H11NO4',
        'Letter': 'DOPA',
        'MolWeight': '197.068807832',
        'SMILES': 'N[C@@H](Cc1ccc(O)c(O)c1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-2-Aminobutyric acid/(2S)-2-aminobutanoic acid': { # CHECKED!
        'Code': 'Abu/hAla',
        'Formula': 'C4H9NO2',
        'Letter': 'Abu/hAla',
        'MolWeight': '103.063328528',
        'SMILES': 'CC[C@H](N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'dimethylarginine/(2S)-5-(diaminomethylideneamino)-2-(dimethylamino)pentanoic acid': { # THIS SHOULD END THE AA CHAIN? OR MAKE A LONG BACKBONE?
        'Code': 'ADMA',
        'Formula': 'C8H18N4O2',
        'Letter': 'ADMA',
        'MolWeight': '202.142975816',
        'SMILES': 'N(C)(C)[C@@H](CCCN=C(N)N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'N-(2-Aminoethyl)glycine/2-(2-aminoethylamino)acetic acid': { # CHECKED!
        'Code': 'Aeg',
        'Formula': 'C4H10N2O2',
        'Letter': 'Aeg',
        'MolWeight': '118.07422756',
        'SMILES': 'NCCNCC(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '2-Aminoisobutyric acid/2-amino-2-methylpropanoic acid': { # CHECKED!
        'Code': 'Aib',
        'Formula': 'C4H9NO2',
        'Letter': 'Aib',
        'MolWeight': '103.063328528',
        'SMILES': 'NC(C)(C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Allylglycine/(2S)-2-aminopent-4-enoic acid': { # CHECKED!
        'Code': 'Alg',
        'Formula': 'C5H9NO2',
        'Letter': 'Alg',
        'MolWeight': '115.063328528',
        'SMILES': 'N[C@@H](CC=C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-azetidine-2-carboxylic acid': { # CHECKED!
        'Code': 'Aze',
        'Formula': 'C4H7NO2',
        'Letter': 'Aze',
        'MolWeight': '101.047678464',
        'SMILES': 'N1CC[C@H]1C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-canavanine/(2S)-2-amino-4-(diaminomethylideneamino)oxybutanoic acid': { # CHECKED!
        'Code': 'Can',
        'Formula': 'C5H12N4O3',
        'Letter': 'Can',
        'MolWeight': '176.090940244',
        'SMILES': 'N[C@@H](CCON=C(N)N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(L/2S)-2,4-diaminobutanoic acid': { # CHECKED!
        'Code': 'Dab',
        'Formula': 'C4H10N2O2',
        'Letter': 'Dab',
        'MolWeight': '118.07422756',
        'SMILES': 'NCC[C@H](N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'dehydroalanine/2-aminoprop-2-enoic acid': { # CHECKED!
        'Code': 'Dha',
        'Formula': 'C3H5NO2',
        'Letter': 'Dha',
        'MolWeight': '87.0320284',
        'SMILES': 'NC(=C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Homoarginine/(2S)-2-amino-6-(diaminomethylideneamino)hexanoic acid': { # CHECKED!
        'Code': 'hArg',
        'Formula': 'C7H16N4O2',
        'Letter': 'hArg',
        'MolWeight': '188.127325752',
        'SMILES': 'N[C@@H](CCCCN=C(N)N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-methionine sulfoxide/(2S)-2-amino-4-methylsulfinylbutanoic acid': { # CHECKED!
        'Code': 'Met(o)',
        'Formula': 'C5H11NO3S',
        'Letter': 'Met(o)',
        'MolWeight': '165.045964212',
        'SMILES': 'N[C@@H](CC[S](=O)C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Norleucine/(2S)-2-aminohexanoic acid': { # CHECKED!
        'Code': 'Nle/α-Ahx',
        'Formula': 'C6H13NO2',
        'Letter': 'Nle/α-Ahx',
        'MolWeight': '131.094628656',
        'SMILES': 'N[C@@H](CCCC)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Norvaline/(2S)-2-aminopentanoic acid': { # CHECKED!
        'Code': 'Nva/Ape',
        'Formula': 'C5H11NO2',
        'Letter': 'Nva/Ape',
        'MolWeight': '117.078978592',
        'SMILES': 'N[C@@H](CCC)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'l-Pipecolic acid/(2S)-piperidine-2-carboxylic acid': { # CHECKED!
        'Code': 'Pip',
        'Formula': 'C6H11NO2',
        'Letter': 'Pip',
        'MolWeight': '129.078978592',
        'SMILES': 'N1[C@@H](CCCC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-selenomethionine/(2S)-2-amino-4-methylselanylbutanoic acid': { # CHECKED!
        'Code': 'Sem/SeMet',
        'Formula': 'C5H11NO2Se',
        'Letter': 'Sem/SeMet',
        'MolWeight': '196.995499892',
        'SMILES': 'N[C@@H](CC[Se]C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Telluromethionine/(2S)-2-amino-4-methyltellanylbutanoic acid': { # CHECKED!
        'Code': 'Tem/TeMet',
        'Formula': 'C5H11NO2Te',
        'Letter': 'Tem/TeMet',
        'MolWeight': '246.985202992',
        'SMILES': 'N[C@@H](CC[Te]C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'p-Aminohexahydrophenylalanin/(2S)-2-amino-3-(4-aminocyclohexyl)propanoic acid ': { # CHECKED!
        'Code': 'Aca',
        'Formula': 'C9H18N2O2',
        'Letter': 'Aca',
        'MolWeight': '186.136827816',
        'SMILES': 'N[C@@H](CC1CCC(N)CC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '3-(aminomethyl)cyclobutane-1-carboxylic acid ': { # CHECKED!
        'Code': 'ACCA',
        'Formula': 'C6H11NO2',
        'Letter': 'ACCA',
        'MolWeight': '129.078978592',
        'SMILES': 'NCC1CC(C1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '6-aminohexanoic acid': {   # CHECKED!
        'Code': 'ε-Ahx',
        'Formula': 'C6H13NO2',
        'Letter': 'ε-Ahx',
        'MolWeight': '131.094628656',
        'SMILES': 'NCCCCCC(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-3-(4-aminomethylcyclohexyl)propanoic acid': { # CHECKED!
        'Code': 'Ama',
        'Formula': 'C10H20N2O2',
        'Letter': 'Ama',
        'MolWeight': '200.15247788',
        'SMILES': 'N[C@@H](CC1CCC(CN)CC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '4-(Aminomethyl)phenylalanine/(2S)-2-amino-3-[4-(aminomethyl)phenyl]propanoic acid': { # CHECKED!
        'Code': 'Amf',
        'Formula': 'C10H14N2O2',
        'Letter': 'Amf',
        'MolWeight': '194.105527688',
        'SMILES': 'N[C@@H](Cc1ccc(CN)cc1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '5-amino-2-nitrobenzoic acid': { # CHECKED!
        'Code': 'Anb',
        'Formula': 'C7H6N2O4',
        'Letter': 'Anb',
        'MolWeight': '182.032756672',
        'SMILES': 'Nc1ccc([N+]([O-])=O)c(c1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Cyclohexylalanine/(2S)-2-amino-3-cyclohexylpropanoic acid': { # CHECKED!
        'Code': 'Cha',
        'Formula': 'C9H17NO2',
        'Letter': 'Cha',
        'MolWeight': '171.125928784',
        'SMILES': 'N[C@@H](CC1CCCCC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Cyclohexylglycine/(2S)-2-amino-2-cyclohexylacetic acid': { # CHECKED!
        'Code': 'Chg',
        'Formula': 'C8H15NO2',
        'Letter': 'Chg',
        'MolWeight': '157.11027872',
        'SMILES': 'N[C@@H](C1CCCCC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-3-(2-cyanopyridin-4-yl)propanoic acid': { # CHECKED!
        'Code': 'Cpa',
        'Formula': 'C9H9N3O2',
        'Letter': 'Cpa',
        'MolWeight': '191.069476528',
        'SMILES': 'N[C@@H](Cc1ccnc(c1)C#N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Cycloleucine/1-aminocyclopentane-1-carboxylic acid': { # CHECKED!
        'Code': 'CycL',
        'Formula': 'C6H11NO2',
        'Letter': 'CycL',
        'MolWeight': '129.078978592',
        'SMILES': 'NC1(CCCC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-4,4-difluoro butanoic acid': { # CHECKED!
        'Code': 'DfeGly',
        'Formula': 'C4H7F2NO2',
        'Letter': 'DfeGly',
        'MolWeight': '139.044484904',
        'SMILES': 'N[C@@H](CC(F)F)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Difluoromethionine/(2S)-2-amino-4-(difluoromethylsulfanyl)butanoic acid': { # CHECKED!
        'Code': 'DFM',
        'Formula': 'C5H9F2NO2S',
        'Letter': 'DFM',
        'MolWeight': '185.032205968',
        'SMILES': 'N[C@@H](CCSC(F)F)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '4,4-Difluoro-L-norvaline/(2S)-2-amino-4,4-difluoro pentanoic acid': { # CHECKED!
        'Code': 'DfpGly',
        'Formula': 'C5H9F2NO2',
        'Letter': 'DfpGly',
        'MolWeight': '153.060134968',
        'SMILES': 'N[C@@H](CC(F)(F)C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Dinitrophenyl-lysine/(2S)-2-amino-6-(2,4-dinitroanilino)hexanoic acid': { # CHECKED!
        'Code': 'Dnp-Lys',
        'Formula': 'C12H16N4O6',
        'Letter': 'Dnp-Lys',
        'MolWeight': '312.10698423199995',
        'SMILES': 'N[C@@H](CCCCNc1ccc(cc1[N+]([O-])=O)[N+]([O-])=O)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '4-Fluoro-L-phenylalanine/(2S)-2-amino-3-(4-fluorophenyl)propanoic acid': { # CHECKED!
        'Code': '4F-Phe',
        'Formula': 'C9H10FNO2',
        'Letter': '4F-Phe',
        'MolWeight': '183.06955678',
        'SMILES': 'N[C@@H](Cc1ccc(F)cc1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '5-Fluoro-L-tryptophan/(2S)-2-amino-3-(5-fluoro-1H-indol-3-yl)propanoic acid': { # CHECKED!
        'Code': '5F-Trp',
        'Formula': 'C11H11FN2O2',
        'Letter': '5F-Trp',
        'MolWeight': '222.080455812',
        'SMILES': 'N[C@@H](Cc1cNc2ccc(F)cc12)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '4-Guanidinophenylalanine/(2S)-2-amino-3-[4-(diaminomethylideneamino)phenyl]propanoic acid': { # CHECKED!
        'Code': 'F(gua)',
        'Formula': 'C10H14N4O2',
        'Letter': 'F(gua)',
        'MolWeight': '222.111675688',
        'SMILES': 'N[C@@H](Cc1ccc(cc1)N=C(N)N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-4-cyclohexylbutanoic acid': { # CHECKED!
        'Code': 'hCha',
        'Formula': 'C10H19NO2',
        'Letter': 'hCha',
        'MolWeight': '185.141578848',
        'SMILES': 'N[C@@H](CCC1CCCCC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'l-2-indanylglycine/(2S)-2-amino-2-(2,3-dihydro-1H-inden-2-yl)acetic acid': { # CHECKED!
        'Code': 'Igl',
        'Formula': 'C11H13NO2',
        'Letter': 'Igl',
        'MolWeight': '191.094628656',
        'SMILES': 'N[C@@H](C1Cc2ccccc2C1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-4-fluorobutanoic acid': { # CHECKED!
        'Code': 'MfeGly',
        'Formula': 'C4H8FNO2',
        'Letter': 'MfeGly',
        'MolWeight': '121.053906716',
        'SMILES': 'N[C@@H](CCF)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '2-Methylleucine/(S)-2-Amino-2,4-dimethylpentanoic acid': { # CHECKED!
        'Code': 'MLeu',
        'Formula': 'C8H17NO2',
        'Letter': 'MLeu',
        'MolWeight': '159.125928784',
        'SMILES': 'N[C@@](CC(C)C)(C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-1-Naphthylalanine/(2S)-2-amino-3-naphthalen-1-ylpropanoic acid': { # CHECKED!
        'Code': '1-Nal',
        'Formula': 'C13H13NO2',
        'Letter': '1-Nal',
        'MolWeight': '215.094628656',
        'SMILES': 'N[C@@H](Cc1cccc2ccccc12)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '3-(2-Naphthyl)-L-alanine/(2S)-2-amino-3-naphthalen-2-ylpropanoic acid': { # CHECKED!
        'Code': '2-Nal',
        'Formula': 'C13H13NO2',
        'Letter': '2-Nal',
        'MolWeight': '215.094628656',
        'SMILES': 'N[C@@H](Cc1ccc2ccccc2c1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Octahydroindole-2-Carboxylic Acid/(2S,3aS,7aR)-2,3,3a,4,5,6,7,7a-octahydro-1H-indole-2-carboxylic acid': { # CHECKED!
        'Code': 'Oic',
        'Formula': 'C9H15NO2',
        'Letter': 'Oic',
        'MolWeight': '169.11027872',
        'SMILES': 'N([C@@H]1CCCC[C@H]1C2)[C@@H]2C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Phenylglycine/(2S)-2-amino-2-phenylacetic acid': { # CHECKED!
        'Code': 'Phg',
        'Formula': 'C8H9NO2',
        'Letter': 'Phg',
        'MolWeight': '151.063328528',
        'SMILES': 'N[C@H](C(=O)O)c1ccccc1',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Octahydroindole-2-carboxylic acid/(2S,3aS,7aS)-2,3,3a,4,5,6,7,7a-octahydro-1H-indole-2-carboxylic acid': { # CHECKED!
        'Code': 'Phi',
        'Formula': 'C9H15NO2',
        'Letter': 'Phi',
        'MolWeight': '169.11027872',
        'SMILES': 'N([C@H]1CCCC[C@H]1C2)[C@@H]2C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-3-(4H-selenopheno[3,2-b]pyrrol-6-yl)propanoic acid (selenolo[3,2-b]pyrrole)': { # CHECKED!
        'Code': 'Sep',
        'Formula': 'C15H15N3O2Se2',
        'Letter': 'Sep',
        'MolWeight': '428.94946932000005',
        'SMILES': 'N[C@@H](Cc1c[nH]c2cc[se]c12)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-4,4,4-trifluorobutanoic acid': { # CHECKED!
        'Code': 'TfeGly',
        'Formula': 'C4H6F3NO2',
        'Letter': 'TfeGly',
        'MolWeight': '157.035063092',
        'SMILES': 'N[C@@H](CC(F)(F)F)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-2-(oxolan-3-yl)acetic acid': { # CHECKED!
        'Code': 'Thfg',
        'Formula': 'C6H11NO3',
        'Letter': 'Thfg',
        'MolWeight': '145.073893212',
        'SMILES': 'N[C@@H](C1CCOC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-2-Thienylalanine/(2S)-2-amino-3-thiophen-2-ylpropanoic acid': { # CHECKED!
        'Code': 'Thi2',
        'Formula': 'C7H9NO2S',
        'Letter': 'Thi2',
        'MolWeight': '171.035399528',
        'SMILES': 'N[C@@H](Cc1cccs1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '3-(3-Thienyl)-l-alanine/(2S)-2-amino-3-thiophen-3-ylpropanoic acid': { # CHECKED!
        'Code': 'Thi3',
        'Formula': 'C7H9NO2S',
        'Letter': 'Thi3',
        'MolWeight': '171.035399528',
        'SMILES': 'N[C@@H](Cc1ccsc1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-Thioproline/(4R)-1,3-thiazolidine-4-carboxylic acid ': { # CHECKED!
        'Code': 'Thp',
        'Formula': 'C4H7NO2S',
        'Letter': 'Thp',
        'MolWeight': '133.019749464',
        'SMILES': 'N1[C@@H](CSC1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'Tetrahydro-3-isoquinoline carboxylic acid/1,2,3,4-tetrahydroisoquinoline-3-carboxylic acid': { # CHECKED!
        'Code': 'Tic',
        'Formula': 'C10H11NO2',
        'Letter': 'Tic',
        'MolWeight': '177.078978592',
        'SMILES': 'N1C(Cc2ccccc2C1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-tert-Leucine/(2S)-2-amino-3,3-dimethylbutanoic acid': { # CHECKED!
        'Code': 'Tle',
        'Formula': 'C6H13NO2',
        'Letter': 'Tle',
        'MolWeight': '131.094628656',
        'SMILES': 'N[C@@H](C(C)(C)C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '4-Cyano-L-Phenylalanine/(2S)-2-amino-3-(4-cyanophenyl)propanoic acid': { # CHECKED!
        'Code': 'CN-Phe',
        'Formula': 'C10H10N2O2',
        'Letter': 'CN-Phe',
        'MolWeight': '190.07422756',
        'SMILES': 'N[C@@H](Cc1ccc(cc1)C#N)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '3-Chloro-L-tyrosine/(2S)-2-amino-3-(3-chloro-4-hydroxyphenyl)propanoic acid ': { # CHECKED!
        'Code': '3CY',
        'Formula': 'C9H10ClNO3',
        'Letter': '3CY',
        'MolWeight': '215.03492086',
        'SMILES': 'N[C@@H](Cc1ccc(O)c(Cl)c1)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '3-Nitro-L-tyrosine/(2S)-2-amino-3-(4-hydroxy-3-nitrophenyl)propanoic acid ': { # CHECKED!
        'Code': '3NY',
        'Formula': 'C9H10N2O5',
        'Letter': '3NY',
        'MolWeight': '226.05897142',
        'SMILES': 'N[C@@H](Cc1ccc(O)c(c1)[N+]([O-])=O)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '4-Benzoyl-l-phenylalanine/(2S)-2-amino-3-(4-benzoylphenyl)propanoic acid ': { # CHECKED!
        'Code': 'Bpa',
        'Formula': 'C16H15NO3',
        'Letter': 'Bpa',
        'MolWeight': '269.10519334',
        'SMILES': 'N[C@@H](Cc1ccc(cc1)C(=O)c2ccccc2)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-2,3-Diaminopropionic acid/(2S)-2,3-diaminopropanoic acid ': { # CHECKED!
        'Code': 'Dap',
        'Formula': 'C3H8N2O2',
        'Letter': 'Dap',
        'MolWeight': '104.058577496',
        'SMILES': 'N[C@@H](CN)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'DiZPK/(2S)-2-amino-6-[3-(3-methyldiazirin-3-yl)propylcarbamoylamino]hexanoic acid ': { # CHECKED!
        'Code': 'DiZPK',
        'Formula': 'C12H23N5O3',
        'Letter': 'DiZPK',
        'MolWeight': '285.180089596',
        'SMILES': 'N[C@@H](CCCCNC(=O)NCCCC1(N=N1)C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-(7-hydroxycoumarin-4-yl) ethylglycine/(2R)-2-amino-4-(7-hydroxy-2-oxochromen-4-yl)butanoic acid': { # CHECKED!
        'Code': 'Hco',
        'Formula': 'C13H13NO5',
        'Letter': 'Hco',
        'MolWeight': '263.07937251600003',
        'SMILES': 'N[C@H](CCC1=CC(=O)Oc2cc(O)ccc12)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-3-(4-(1-(6-nitrobenzo[d][1,3]dioxol-5-yl)ethoxy)phenyl)propanoic acid': { # CHECKED!
        'Code': 'NPY',
        'Formula': 'C18H18N2O7',
        'Letter': 'NPY',
        'MolWeight': '374.1114009159999',
        'SMILES': 'N[C@@H](Cc1ccc(cc1)OC(C)c1cc2OCOc2cc1[N+]([O-])=O)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(2S)-2-amino-6-(4-azido-benzyloxycarbonylamino)hexanoic acid ': { # CHECKED!
        'Code': 'PABK',
        'Formula': 'C14H19N5O4',
        'Letter': 'PABK',
        'MolWeight': '321.143704088',
        'SMILES': 'N[C@@H](CCCCNC(=O)OCc1ccc(cc1)N=[N+]=[N-])C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '(S)-2-Amino-4-azidobutanoic acid/(2S)-2-amino-4-azidobutanoic acid ': { # CHECKED!
        'Code': 'Aha',
        'Formula': 'C4H8N4O2',
        'Letter': 'Aha',
        'MolWeight': '144.064725496',
        'SMILES': 'N[C@@H](CCN=[N+]=[N-])C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    '4-Azido-L-phenylalanine/(2S)-2-amino-3-(4-azidophenyl)propanoic acid ': { # CHECKED!
        'Code': 'AzF',
        'Formula': 'C9H10N4O2',
        'Letter': 'AzF',
        'MolWeight': '206.08037556',
        'SMILES': 'N[C@@H](Cc1ccc(cc1)N=[N+]=[N-])C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'L-homopropargylglycine/(2S)-2-aminohex-5-ynoic acid ': { # CHECKED!
        'Code': 'Hpg',
        'Formula': 'C6H9NO2',
        'Letter': 'Hpg',
        'MolWeight': '127.063328528',
        'SMILES': 'N[C@@H](CCC#C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'N-|A-propargyloxycarbonyl-L-lysine/(2S)-2-amino-6-{[(prop-2-yn-1-yloxy)carbonyl]amino}hexanoic acid': { # CHECKED!
        'Code': 'Plk',
        'Formula': 'C10H16N2O4',
        'Letter': 'Plk',
        'MolWeight': '228.111006992',
        'SMILES': 'N[C@@H](CCCCNC(=O)OCC#C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    },
    'S-Allylcysteine/(2R)-2-amino-3-prop-2-enylsulfanylpropanoic acid ': { # CHECKED!
        'Code': 'Sac',
        'Formula': 'C6H11NO2S',
        'Letter': 'Sac',
        'MolWeight': '161.051049592',
        'SMILES': 'N[C@@H](CSCC=C)C(=O)O',
        'cterm': False,
        'disulphide': False,
        'ester': False,
        'nterm': False
    }
    }