[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "p2smi"
version = "2.0.0"
description = "A toolkit enabling SMILES generation and property analysis for noncanonical and cyclized peptides."
readme = "README.md"
license = "MIT"
authors = [{ name="Aaron Feller", email="aaronleefeller@gmail.com" }]
dependencies = ["rdkit", "numpy"]
requires-python = ">=3.9"
classifiers = [
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
]

[project.scripts]
generate-peptides = "p2smi.genPeps:main"
fasta2smi = "p2smi.fasta2smi:main"
add-amino-acid = "p2smi.add_amino:main"
import-lipid-modifiers = "p2smi.import_lipids:main"
modify-smiles = "p2smi.chemMods:main"
smiles-props = "p2smi.chemProps:main"
synthesis-check = "p2smi.synthRules:main"

[project.optional-dependencies]
dev = ["pytest",
        "black==25.9.0",
        "flake8",
        "pytest-cov",
        "pre-commit"]

[tool.setuptools.packages.find]
include = ["p2smi*"]

[tool.black]
target-version = ["py39"]
line-length = 88
